# Generated by Django 4.0.6 on 2022-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuseoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuseo',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
