# Generated by Django 4.1 on 2022-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuseoapp', '0002_alter_yuseo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuseo',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
        migrations.AddField(
            model_name='yuseo',
            name='voice',
            field=models.FileField(null=True, upload_to='voice/'),
        ),
        migrations.AlterField(
            model_name='yuseo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
