# Generated by Django 4.1 on 2022-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_remove_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
