# Generated by Django 4.1 on 2022-08-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0005_remove_question_day_remove_question_present'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionSeven',
        ),
    ]
