# Generated by Django 4.1 on 2022-08-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0006_rename_question_questionseven'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerSeven',
        ),
    ]
