# Generated by Django 4.1 on 2022-08-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0007_rename_answer_answerseven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerseven',
            old_name='question',
            new_name='q_id',
        ),
        migrations.AlterField(
            model_name='answerseven',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionseven',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
