# Generated by Django 4.1 on 2022-08-17 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuseotext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuseotext',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yuseotext',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
