# Generated by Django 4.1 on 2022-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuseotext', '0003_alter_yuseotext_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuseotext',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
